name: age_yubikey_pgp
description: Age Encryption Yubikey PGP plugin
version: 1.0.0
homepage: https://github.com/Producement/age-yubikey-pgp

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.3.1
  bech32: ^0.2.1
  collection: ^1.16.0
  convert: ^3.0.1
  crypto: ^3.0.2
  cryptography: ^2.0.5
  logging: ^1.0.2
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.11
  lints: ^2.0.0
  mockito: ^5.1.0
  test: ^1.16.0