name: age_yubikey_pgp
description: Age Encryption Yubikey PGP plugin
version: 0.0.9
homepage: https://github.com/Producement/age-yubikey-pgp

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  args: ^2.3.1
  convert: ^3.0.2
  cryptography: ^2.0.5
  logging: ^1.0.2
  dage: ^1.0.6
  yubikit_openpgp: ^1.0.12
  collection: ^1.16.0
  pointycastle: ^3.6.0

dev_dependencies:
  build_runner: ^2.1.11
  lints: ^2.0.0
  mockito: ^5.1.0
  test: ^1.16.0

dependency_overrides:
  cryptography:
    git:
      url: https://github.com/Producement/cryptography.git
      ref: master
      path: cryptography