// Mocks generated by Mockito 5.2.0 from annotations
// in age_yubikey_pgp/test/yubikey/yubikey_smartcard_interface_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;
import 'dart:typed_data' as _i3;

import 'package:age_yubikey_pgp/src/yubikey/pin_provider.dart' as _i8;
import 'package:age_yubikey_pgp/src/yubikey/smartcard/curve.dart' as _i5;
import 'package:age_yubikey_pgp/src/yubikey/smartcard/keyslot.dart' as _i4;
import 'package:age_yubikey_pgp/src/yubikey/smartcard/smartcard.dart' as _i6;
import 'package:age_yubikey_pgp/src/yubikey/yubikey_smartcard_command.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [YubikeySmartCardCommand].
///
/// See the documentation for Mockito's code generation for more information.
class MockYubikeySmartCardCommand extends _i1.Mock
    implements _i2.YubikeySmartCardCommand {
  MockYubikeySmartCardCommand() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Uint8List verifyAdmin(String? pin) =>
      (super.noSuchMethod(Invocation.method(#verifyAdmin, [pin]),
          returnValue: _i3.Uint8List(0)) as _i3.Uint8List);
  @override
  _i3.Uint8List verifyPin(String? pin) =>
      (super.noSuchMethod(Invocation.method(#verifyPin, [pin]),
          returnValue: _i3.Uint8List(0)) as _i3.Uint8List);
  @override
  _i3.Uint8List generateKey(_i4.KeySlot? keySlot) =>
      (super.noSuchMethod(Invocation.method(#generateKey, [keySlot]),
          returnValue: _i3.Uint8List(0)) as _i3.Uint8List);
  @override
  _i3.Uint8List setFingerprint(
          _i4.KeySlot? keySlot, _i5.ECCurve? curve, _i3.Uint8List? publicKey,
          [int? timestamp]) =>
      (super.noSuchMethod(
          Invocation.method(
              #setFingerprint, [keySlot, curve, publicKey, timestamp]),
          returnValue: _i3.Uint8List(0)) as _i3.Uint8List);
  @override
  _i3.Uint8List setKeyAttributes(_i4.KeySlot? keySlot, _i5.ECCurve? curve) =>
      (super.noSuchMethod(
          Invocation.method(#setKeyAttributes, [keySlot, curve]),
          returnValue: _i3.Uint8List(0)) as _i3.Uint8List);
  @override
  _i3.Uint8List getECPublicKey(_i4.KeySlot? keySlot) =>
      (super.noSuchMethod(Invocation.method(#getECPublicKey, [keySlot]),
          returnValue: _i3.Uint8List(0)) as _i3.Uint8List);
  @override
  _i3.Uint8List getSharedSecret(_i3.Uint8List? publicKey) =>
      (super.noSuchMethod(Invocation.method(#getSharedSecret, [publicKey]),
          returnValue: _i3.Uint8List(0)) as _i3.Uint8List);
}

/// A class which mocks [SmartCardInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockSmartCardInterface extends _i1.Mock
    implements _i6.SmartCardInterface {
  MockSmartCardInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i3.Uint8List> sendCommand(List<int>? input) =>
      (super.noSuchMethod(Invocation.method(#sendCommand, [input]),
              returnValue: Future<_i3.Uint8List>.value(_i3.Uint8List(0)))
          as _i7.Future<_i3.Uint8List>);
}

/// A class which mocks [PinProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPinProvider extends _i1.Mock implements _i8.PinProvider {
  MockPinProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String adminPin() =>
      (super.noSuchMethod(Invocation.method(#adminPin, []), returnValue: '')
          as String);
  @override
  String pin() =>
      (super.noSuchMethod(Invocation.method(#pin, []), returnValue: '')
          as String);
}
